### PR TITLE
show 404 page on bad routes

### LINKED ISSUE #316: Static route 404 page not working
## Expected Behavior
1. Visit https://mit-open-rc.odl.mit.edu/does/not/exist
2. You should see a 404 page

## Current Behavior
Instead, a generic fallback error page is displayed.

## Possible Solution
This bug was probably introduced in #250; while updating react router, we changed some frontend error handling / routes stuff.

### PR DESCRIPTION
**Pull request by ChristopherChudzicki**
# What are the relevant tickets?
Closes #316 

# Description (What does it do?)
Renders react 404 on unmatched routes.

# How can this be tested?
1. Visit https://mit-open-rc.odl.mit.edu/bad/route ... you will see a generic "Something went wrong" page.
2. On this branch, with `DEBUG=False`, visit http://localhost:8063/bad/route. You should see a 404 page.

### CODE REVIEW

File: frontends/mit-open/src/test-utils/index.tsx [hunk 1]
```diff
@@ -44,15 +44,7 @@ const renderRoutesWithProviders = (
...
-  const router = createMemoryRouter(
-    [
-      {
-        errorElement: <RethrowError />,
-        children: routes,
-      },
-    ],
-    { initialEntries: [url] },
-  )
+  const router = createMemoryRouter(routes, { initialEntries: [url] })
```
Comment (ChristopherChudzicki) [inline frontends/mit-open/src/test-utils/index.tsx:47]: `< RethrowError />` is still renderd by `renderWithProviders`, but no longer by `renderTestApp`, which now renders the App's routes normally—the same way the `<App />` component does.

The point of RethrowError was to make errors during testing more visible. The `console.error` in `<ErrorPage />` achieves the same thing for `renderTestApp` (since we fail our unit tests when there are console errors).

**Review by abeglova — APPROVED** [review]
